### ISSUE TITLE
[404 Page] Visual hiccup on mobile

### ISSUE THREAD

**Issue by VictorWesterlund** [VictorWesterlund/victorwesterlund.com#13]
https://github.com/VictorWesterlund/victorwesterlund.com/blob/af9fbba1e481d8d3cc6ded32c8931a8426d6dc3a/public/netwatch/assets/css/style.css#L84

Fixed header width causes overflow on screens smaller than "min-width + padding". [Demo](https://user-images.githubusercontent.com/35688133/103378654-4fb18e00-4ae3-11eb-9622-b89ae4df0e45.png)

Issue can be fixed with:

```css
@media screen and (max-width: 950px) {
    #keystoneLogo {
        width: 100%;
        min-width: unset;
    }
}
```
